version: "3.9"

services:
  app:
    build: .
    container_name: pokemon_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_NAME: pokemon

  db:
    image: postgres:15
    container_name: pokemon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: pokemon
    ports:
      - "5433:5432"   # map container 5432 â†’ host 5433
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
